mutation updateUserAnswerOpen($questionId: ID!, $answerText: String!) { 
    updateUserAnswerOpen(
      questionId: $questionId,
      answerText: $answerText
    ) {
      firstTouched
      lastTouched
      countTouched
      status
    } 
  }