mutation createUser($pollId: ID!, $username: String!, $password: String!) {
    createUser(
      pollId: $pollId,
      username: $username,
      password: $password
    ) {
      user {
        username
        currentPoll {
          id
        }
        email
        password
      }
    }
  }
