mutation createUser($pollId: ID!, $browserInfo: String!, $osInfo: String!) {
    createUser(
      pollId: $pollId,
      browserInfo: $browserInfo,
      osInfo: $osInfo,
    ) {
      user {
        username
        currentPoll {
          id
        }
      }
    }
  }
