mutation createUser($challengeCode: String!, $username: String!, $email: String!, $password: String!) {
    createUser(
      challengeCode: $challengeCode,
      username: $username,
      email: $email,
      password: $password
    ) {
      user {
        username
        currentProject {
          projectName
        }
        currentChallenge {
          context
        }
        email
        password
      }
    }
  }
