mutation joinProject($projectCode: String!) {
    joinProject(
      projectCode: $projectCode
    ) {
      project {
        projectName
        projectDescription
        projectCode
      }
    }
  }