# Change so challenge code is read from requesting user. No challenge code argument needed

query aChallenge {
    aChallenge {
      context
      city
      year
      contactInfo {
        username
        email
        phone
      }
      challengeCode
      challengedateSet {
        id
        eventName
        eventLocation
        eventDate
        eventEndTime
        eventStartTime
        eventNotes
      }
    }
  } 
  